:concurrency: 25
:queues:
  - critical
  - default
  - mailers # to remove
  - active_storage_analysis # to remove
  - sva # to remove
  - webhooks_v1 # to remove
  - api_entreprise # to remove
  - cron # to remove
  - low_priority # to remove
  - low
  - exports
  - archives
  - purge # to remove
  - expires # to remove
