---
replicaCount: 2

image:
  repository: ghcr.io/hnoel/demarche.numerique.gouv.fr
  tag: "main"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

route:
  enabled: true
  host: demarche.numerique.gouv.fr # à surcharger en prod
  tls: true

resources:
  limits:
    cpu: "2"
    memory: "2Gi"
  requests:
    cpu: "1"
    memory: "1Gi"

env:
  - name: DJANGO_SETTINGS_ENV
    value: "production"

# Si tu as besoin de secrets (ex. JWT, DB password) :
secret:
  enabled: true
  name: demarche-numerique-secret
  # les valeurs seront injectées via `kubectl create secret` ou via OpenShift UI
...
